on:
  issues:
    types: [labeled]

jobs:
  needs-crash-report:
    name: This job keeps an eye on crash reports without a link to Sentry.
    runs-on: ubuntu-latest
    steps:
      - id: needs_crash_report
        uses: st3fan/needs-crash-report-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          crash-label: "crash"
          needs-crash-report-label: "needs-crash-report"
          crash-reporter: "https://sentry.prod.mozaws.net/"
